# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1beta
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: gh-pages-secret
data:
  env_vars:
    # Username of github user used for deploy
    - name: GH_USERNAME
      value: "super secret github username"
    # Email of github user used for deploy
    - name: GH_EMAIL
      value: "super secret github email"
  files:
    # Generate ssh key https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
    # Add it to account you will use to deploy to github here https://github.com/settings/keys
    - path: .ssh/id_rsa_semaphoreci_ghpages_deploy
      # Could be created by
      # - `base64 -w 0 /path/to/file` and put in
      # - upload in https://<your-namesace>.semaphoreci.com/secrets
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
